# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWM0MDMyZjIwMWY1ZThhYTE2OWRhNGU5ZDc5NjRmZDI0Yjg2OWNkOGUzMWM0MWM1NTYyYmE3OTJhNTJhODNiNzVjMzkwMmM0ZjQwMjMyMDQxYTQxODQ5ZDE5YTIzZWFlMGY4NjgyNmY0YzFiNTcxYjNkMWQzYTFiOTE4MjlkYTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
