# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmEyOWIyODhkYTBhNjdiYzczNWE0NjUyZjM1NmI1MGYzNGNmZTEyM2ZmNmJmNmE4NTQ2YzYyNTIxODMwNzMzNTc2ZTE5YzQxZDUxMDM3NTgwNTRhOGI5YWY0MWJiYWFhMWVlYjRiNDFjMzliOTMwNGQwZDA0ZTg4YWYwMzk3NWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
