# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTA0ODQyYjc1NTNkMWRhZTk1ZWRmZjdiOWZlOWNjM2UyNzEzMTFiZjVmMTJkMTAwODE5NWUxNWY4YmZmZDFmMzU1ZDhjYTU1NDY0NTY2OTkyZTM2YzJiMzkxZmY4NDI0N2NkOGY3OGNlNjMxOTkwZmJiMDMwMzI3MzBjZjFkZTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
